/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CoreCrudIndexRouteImport } from './routes/core.crud.index'
import { Route as AuthenticatedCoreCrudDemoIndexRouteImport } from './routes/_authenticated.core.crud.demo.index'
import { Route as AuthenticatedCoreCrudDemoIdRouteImport } from './routes/_authenticated.core.crud.demo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreCrudIndexRoute = CoreCrudIndexRouteImport.update({
  id: '/core/crud/',
  path: '/core/crud/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoreCrudDemoIndexRoute =
  AuthenticatedCoreCrudDemoIndexRouteImport.update({
    id: '/core/crud/demo/',
    path: '/core/crud/demo/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoreCrudDemoIdRoute =
  AuthenticatedCoreCrudDemoIdRouteImport.update({
    id: '/core/crud/demo/$id',
    path: '/core/crud/demo/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/crud/': typeof CoreCrudIndexRoute
  '/core/crud/demo/$id': typeof AuthenticatedCoreCrudDemoIdRoute
  '/core/crud/demo/': typeof AuthenticatedCoreCrudDemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/crud': typeof CoreCrudIndexRoute
  '/core/crud/demo/$id': typeof AuthenticatedCoreCrudDemoIdRoute
  '/core/crud/demo': typeof AuthenticatedCoreCrudDemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/crud/': typeof CoreCrudIndexRoute
  '/_authenticated/core/crud/demo/$id': typeof AuthenticatedCoreCrudDemoIdRoute
  '/_authenticated/core/crud/demo/': typeof AuthenticatedCoreCrudDemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/status'
    | '/api/$'
    | '/api/auth/$'
    | '/core/crud/'
    | '/core/crud/demo/$id'
    | '/core/crud/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/status'
    | '/api/$'
    | '/api/auth/$'
    | '/core/crud'
    | '/core/crud/demo/$id'
    | '/core/crud/demo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/status'
    | '/api/$'
    | '/api/auth/$'
    | '/core/crud/'
    | '/_authenticated/core/crud/demo/$id'
    | '/_authenticated/core/crud/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CoreCrudIndexRoute: typeof CoreCrudIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/crud/': {
      id: '/core/crud/'
      path: '/core/crud'
      fullPath: '/core/crud/'
      preLoaderRoute: typeof CoreCrudIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/core/crud/demo/': {
      id: '/_authenticated/core/crud/demo/'
      path: '/core/crud/demo'
      fullPath: '/core/crud/demo/'
      preLoaderRoute: typeof AuthenticatedCoreCrudDemoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/core/crud/demo/$id': {
      id: '/_authenticated/core/crud/demo/$id'
      path: '/core/crud/demo/$id'
      fullPath: '/core/crud/demo/$id'
      preLoaderRoute: typeof AuthenticatedCoreCrudDemoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCoreCrudDemoIdRoute: typeof AuthenticatedCoreCrudDemoIdRoute
  AuthenticatedCoreCrudDemoIndexRoute: typeof AuthenticatedCoreCrudDemoIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoreCrudDemoIdRoute: AuthenticatedCoreCrudDemoIdRoute,
  AuthenticatedCoreCrudDemoIndexRoute: AuthenticatedCoreCrudDemoIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CoreCrudIndexRoute: CoreCrudIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
