/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedCoreFileUploadsDemoRouteImport } from './routes/_authenticated.core.file-uploads-demo'
import { Route as AuthenticatedCorePaginationDemoRouteImport } from './routes/_authenticated.core.pagination-demo'
import { Route as AuthenticatedCoreSearchFilterDemoRouteImport } from './routes/_authenticated.core.search-filter-demo'
import { Route as AuthenticatedCoreTablesDemoRouteImport } from './routes/_authenticated.core.tables-demo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CoreCrudIndexRouteImport } from './routes/core.crud.index'
import { Route as CoreFileUploadsIndexRouteImport } from './routes/core.file-uploads.index'
import { Route as CorePaginationIndexRouteImport } from './routes/core.pagination.index'
import { Route as CoreSearchFilterIndexRouteImport } from './routes/core.search-filter.index'
import { Route as CoreTablesIndexRouteImport } from './routes/core.tables.index'
import { Route as AuthenticatedCoreCrudDemoIndexRouteImport } from './routes/_authenticated.core.crud-demo.index'
import { Route as AuthenticatedCoreCrudDemoIdRouteImport } from './routes/_authenticated.core.crud-demo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoreFileUploadsDemoRoute =
  AuthenticatedCoreFileUploadsDemoRouteImport.update({
    id: '/core/file-uploads-demo',
    path: '/core/file-uploads-demo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorePaginationDemoRoute =
  AuthenticatedCorePaginationDemoRouteImport.update({
    id: '/core/pagination-demo',
    path: '/core/pagination-demo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoreSearchFilterDemoRoute =
  AuthenticatedCoreSearchFilterDemoRouteImport.update({
    id: '/core/search-filter-demo',
    path: '/core/search-filter-demo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoreTablesDemoRoute =
  AuthenticatedCoreTablesDemoRouteImport.update({
    id: '/core/tables-demo',
    path: '/core/tables-demo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreCrudIndexRoute = CoreCrudIndexRouteImport.update({
  id: '/core/crud/',
  path: '/core/crud/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreFileUploadsIndexRoute = CoreFileUploadsIndexRouteImport.update({
  id: '/core/file-uploads/',
  path: '/core/file-uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorePaginationIndexRoute = CorePaginationIndexRouteImport.update({
  id: '/core/pagination/',
  path: '/core/pagination/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreSearchFilterIndexRoute = CoreSearchFilterIndexRouteImport.update({
  id: '/core/search-filter/',
  path: '/core/search-filter/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreTablesIndexRoute = CoreTablesIndexRouteImport.update({
  id: '/core/tables/',
  path: '/core/tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoreCrudDemoIndexRoute =
  AuthenticatedCoreCrudDemoIndexRouteImport.update({
    id: '/core/crud-demo/',
    path: '/core/crud-demo/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoreCrudDemoIdRoute =
  AuthenticatedCoreCrudDemoIdRouteImport.update({
    id: '/core/crud-demo/$id',
    path: '/core/crud-demo/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/api/$': typeof ApiSplatRoute
  '/core/file-uploads-demo': typeof AuthenticatedCoreFileUploadsDemoRoute
  '/core/pagination-demo': typeof AuthenticatedCorePaginationDemoRoute
  '/core/search-filter-demo': typeof AuthenticatedCoreSearchFilterDemoRoute
  '/core/tables-demo': typeof AuthenticatedCoreTablesDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/crud/': typeof CoreCrudIndexRoute
  '/core/file-uploads/': typeof CoreFileUploadsIndexRoute
  '/core/pagination/': typeof CorePaginationIndexRoute
  '/core/search-filter/': typeof CoreSearchFilterIndexRoute
  '/core/tables/': typeof CoreTablesIndexRoute
  '/core/crud-demo/$id': typeof AuthenticatedCoreCrudDemoIdRoute
  '/core/crud-demo/': typeof AuthenticatedCoreCrudDemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/api/$': typeof ApiSplatRoute
  '/core/file-uploads-demo': typeof AuthenticatedCoreFileUploadsDemoRoute
  '/core/pagination-demo': typeof AuthenticatedCorePaginationDemoRoute
  '/core/search-filter-demo': typeof AuthenticatedCoreSearchFilterDemoRoute
  '/core/tables-demo': typeof AuthenticatedCoreTablesDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/crud': typeof CoreCrudIndexRoute
  '/core/file-uploads': typeof CoreFileUploadsIndexRoute
  '/core/pagination': typeof CorePaginationIndexRoute
  '/core/search-filter': typeof CoreSearchFilterIndexRoute
  '/core/tables': typeof CoreTablesIndexRoute
  '/core/crud-demo/$id': typeof AuthenticatedCoreCrudDemoIdRoute
  '/core/crud-demo': typeof AuthenticatedCoreCrudDemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/core/file-uploads-demo': typeof AuthenticatedCoreFileUploadsDemoRoute
  '/_authenticated/core/pagination-demo': typeof AuthenticatedCorePaginationDemoRoute
  '/_authenticated/core/search-filter-demo': typeof AuthenticatedCoreSearchFilterDemoRoute
  '/_authenticated/core/tables-demo': typeof AuthenticatedCoreTablesDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/core/crud/': typeof CoreCrudIndexRoute
  '/core/file-uploads/': typeof CoreFileUploadsIndexRoute
  '/core/pagination/': typeof CorePaginationIndexRoute
  '/core/search-filter/': typeof CoreSearchFilterIndexRoute
  '/core/tables/': typeof CoreTablesIndexRoute
  '/_authenticated/core/crud-demo/$id': typeof AuthenticatedCoreCrudDemoIdRoute
  '/_authenticated/core/crud-demo/': typeof AuthenticatedCoreCrudDemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/status'
    | '/api/$'
    | '/core/file-uploads-demo'
    | '/core/pagination-demo'
    | '/core/search-filter-demo'
    | '/core/tables-demo'
    | '/api/auth/$'
    | '/core/crud/'
    | '/core/file-uploads/'
    | '/core/pagination/'
    | '/core/search-filter/'
    | '/core/tables/'
    | '/core/crud-demo/$id'
    | '/core/crud-demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/status'
    | '/api/$'
    | '/core/file-uploads-demo'
    | '/core/pagination-demo'
    | '/core/search-filter-demo'
    | '/core/tables-demo'
    | '/api/auth/$'
    | '/core/crud'
    | '/core/file-uploads'
    | '/core/pagination'
    | '/core/search-filter'
    | '/core/tables'
    | '/core/crud-demo/$id'
    | '/core/crud-demo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/status'
    | '/api/$'
    | '/_authenticated/core/file-uploads-demo'
    | '/_authenticated/core/pagination-demo'
    | '/_authenticated/core/search-filter-demo'
    | '/_authenticated/core/tables-demo'
    | '/api/auth/$'
    | '/core/crud/'
    | '/core/file-uploads/'
    | '/core/pagination/'
    | '/core/search-filter/'
    | '/core/tables/'
    | '/_authenticated/core/crud-demo/$id'
    | '/_authenticated/core/crud-demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CoreCrudIndexRoute: typeof CoreCrudIndexRoute
  CoreFileUploadsIndexRoute: typeof CoreFileUploadsIndexRoute
  CorePaginationIndexRoute: typeof CorePaginationIndexRoute
  CoreSearchFilterIndexRoute: typeof CoreSearchFilterIndexRoute
  CoreTablesIndexRoute: typeof CoreTablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/core/file-uploads-demo': {
      id: '/_authenticated/core/file-uploads-demo'
      path: '/core/file-uploads-demo'
      fullPath: '/core/file-uploads-demo'
      preLoaderRoute: typeof AuthenticatedCoreFileUploadsDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/core/pagination-demo': {
      id: '/_authenticated/core/pagination-demo'
      path: '/core/pagination-demo'
      fullPath: '/core/pagination-demo'
      preLoaderRoute: typeof AuthenticatedCorePaginationDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/core/search-filter-demo': {
      id: '/_authenticated/core/search-filter-demo'
      path: '/core/search-filter-demo'
      fullPath: '/core/search-filter-demo'
      preLoaderRoute: typeof AuthenticatedCoreSearchFilterDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/core/tables-demo': {
      id: '/_authenticated/core/tables-demo'
      path: '/core/tables-demo'
      fullPath: '/core/tables-demo'
      preLoaderRoute: typeof AuthenticatedCoreTablesDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/crud/': {
      id: '/core/crud/'
      path: '/core/crud'
      fullPath: '/core/crud/'
      preLoaderRoute: typeof CoreCrudIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/file-uploads/': {
      id: '/core/file-uploads/'
      path: '/core/file-uploads'
      fullPath: '/core/file-uploads/'
      preLoaderRoute: typeof CoreFileUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/pagination/': {
      id: '/core/pagination/'
      path: '/core/pagination'
      fullPath: '/core/pagination/'
      preLoaderRoute: typeof CorePaginationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/search-filter/': {
      id: '/core/search-filter/'
      path: '/core/search-filter'
      fullPath: '/core/search-filter/'
      preLoaderRoute: typeof CoreSearchFilterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/tables/': {
      id: '/core/tables/'
      path: '/core/tables'
      fullPath: '/core/tables/'
      preLoaderRoute: typeof CoreTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/core/crud-demo/': {
      id: '/_authenticated/core/crud-demo/'
      path: '/core/crud-demo'
      fullPath: '/core/crud-demo/'
      preLoaderRoute: typeof AuthenticatedCoreCrudDemoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/core/crud-demo/$id': {
      id: '/_authenticated/core/crud-demo/$id'
      path: '/core/crud-demo/$id'
      fullPath: '/core/crud-demo/$id'
      preLoaderRoute: typeof AuthenticatedCoreCrudDemoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCoreFileUploadsDemoRoute: typeof AuthenticatedCoreFileUploadsDemoRoute
  AuthenticatedCorePaginationDemoRoute: typeof AuthenticatedCorePaginationDemoRoute
  AuthenticatedCoreSearchFilterDemoRoute: typeof AuthenticatedCoreSearchFilterDemoRoute
  AuthenticatedCoreTablesDemoRoute: typeof AuthenticatedCoreTablesDemoRoute
  AuthenticatedCoreCrudDemoIdRoute: typeof AuthenticatedCoreCrudDemoIdRoute
  AuthenticatedCoreCrudDemoIndexRoute: typeof AuthenticatedCoreCrudDemoIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoreFileUploadsDemoRoute: AuthenticatedCoreFileUploadsDemoRoute,
  AuthenticatedCorePaginationDemoRoute: AuthenticatedCorePaginationDemoRoute,
  AuthenticatedCoreSearchFilterDemoRoute:
    AuthenticatedCoreSearchFilterDemoRoute,
  AuthenticatedCoreTablesDemoRoute: AuthenticatedCoreTablesDemoRoute,
  AuthenticatedCoreCrudDemoIdRoute: AuthenticatedCoreCrudDemoIdRoute,
  AuthenticatedCoreCrudDemoIndexRoute: AuthenticatedCoreCrudDemoIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CoreCrudIndexRoute: CoreCrudIndexRoute,
  CoreFileUploadsIndexRoute: CoreFileUploadsIndexRoute,
  CorePaginationIndexRoute: CorePaginationIndexRoute,
  CoreSearchFilterIndexRoute: CoreSearchFilterIndexRoute,
  CoreTablesIndexRoute: CoreTablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
